'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Imports Microsoft.VisualBasic.ApplicationServices

Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        Dim Main_Form As Form

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = FormList(0)
        End Sub

        Private Sub MyApplication_Startup(sender As Object, e As StartupEventArgs) Handles Me.Startup

            Dim a = 0

            If Not My.Computer.FileSystem.FileExists(MyPath & "cfg.ini") Then
                Dim S As String = "[main]"
                S &= vbCrLf & "_link_file_name=Shorcuts.shr"
                S &= vbCrLf & "_width=30"
                S &= vbCrLf & "_offset_position=0"
                S &= vbCrLf & ""

                My.Computer.FileSystem.WriteAllText(MyPath & "cfg.ini", S, False)
            End If

            Load_CFG()

            CreateSpecialFoldersLists()


            If Not My.Computer.FileSystem.FileExists(MyPath & _link_file_name) Then
                GenereteNewFormCFG()
            End If

            LoadGroupsConfiguration()

            For Each F In FormList
                F.Show()
            Next


            frmFixedText.myInstanceNumber = frmElementsGroup.myInstanceNumber
            frmFixedText.TextColor = _fixedtext_text_color
            frmFixedText.OpenedColor = _fixedtext_open_color
            frmFixedText.ClosedColor = _fixedtext_close_color
            frmFixedText.ElementsNumber = _fixedtext_elements_number

            frmFixedText.Show()

            frmMultiClipboard.myInstanceNumber = frmElementsGroup.myInstanceNumber + 1
            frmMultiClipboard.TextColor = _clipboard_text_color
            frmMultiClipboard.OpenedColor = _clipboard_open_color
            frmMultiClipboard.ClosedColor = _clipboard_close_color
            frmMultiClipboard.ElementsNumber = _clipboard_elements_number

            frmMultiClipboard.Show()



            total_width = FormList.Count * (_width + distance_between_form_elements) - distance_between_form_elements

            'Form1.Show()

        End Sub
    End Class
End Namespace

