'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Imports Microsoft.VisualBasic.ApplicationServices

Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        Dim Main_Form As Form

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = My_Settings.Groups(0)
        End Sub

        Private Sub MyApplication_Startup(sender As Object, e As StartupEventArgs) Handles Me.Startup

            Dim a = 0
            My_Settings.MyPath = System.AppDomain.CurrentDomain.BaseDirectory

            If Not My.Computer.FileSystem.FileExists(My_Settings.MyPath & "cfg.ini") Then
                Dim S As String = "[main]"
                S &= vbCrLf & "My_Settings.LinkFileName=Shorcuts.shr"
                S &= vbCrLf & "_width=30"
                S &= vbCrLf & "My_Settings.DefaultOffset=0"
                S &= vbCrLf & ""

                My.Computer.FileSystem.WriteAllText(My_Settings.MyPath & "cfg.ini", S, False)
            End If

            Load_CFG()

            CreateSpecialFoldersLists()


            If Not My.Computer.FileSystem.FileExists(My_Settings.MyPath & My_Settings.LinkFileName) Then
                GenereteNewFormCFG()
            End If

            LoadGroupsConfiguration()

            For Each F In My_Settings.Groups
                F.Show()
            Next


            frmFixedText.myInstanceNumber = frmElementsGroup.myInstanceNumber
            frmFixedText.TextColor = My_Settings.FixedTextTextColor
            frmFixedText.OpenedColor = My_Settings.FixedTextOpenColor
            frmFixedText.ClosedColor = My_Settings.FixedTextCloseColor
            frmFixedText.ElementsNumber = My_Settings.FixedTextElementsNumber

            frmFixedText.Show()

            frmMultiClipboard.myInstanceNumber = frmElementsGroup.myInstanceNumber + 1
            frmMultiClipboard.TextColor = My_Settings.ClipboardTextColor
            frmMultiClipboard.OpenedColor = My_Settings.ClipboardOpenColor
            frmMultiClipboard.ClosedColor = My_Settings.ClipboardCloseColor
            frmMultiClipboard.ElementsNumber = My_Settings.ClipboardElementsNumber

            frmMultiClipboard.Show()



            My_Settings.TotalWidth = My_Settings.Groups.Count * (_width + My_Settings.SpaceBetweenBars) - My_Settings.SpaceBetweenBars

            'Form1.Show()

        End Sub
    End Class
End Namespace

